name: CI

on:
  push:
    branches: 
      - '*'
    tags:
      - v*
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2sdk:latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apk add build-base p7zip
    
    - name: Compile project
      run: |
        make rebuild ${{ matrix.flags }}

    - name: Get short SHA
      id: slug
      run: |
        echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
        echo "date=$(date +%d-%m-%Y)" >> $GITHUB_OUTPUT

    
    - name: pack project
      run: |
        7z a -t7z ${{ github.event.repository.name }}.7z *.a LICENSE README.md include/SIOCookie.h

    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ github.event.repository.name }}-${{ steps.slug.outputs.sha8 }}-${{ steps.slug.outputs.date }}
        path: '*.a'

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Create release
      if: github.ref == 'refs/heads/main'
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Latest SIOCookie.a"
        files: |
             ${{ github.event.repository.name }}.7z

    - name: Create release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: "${{ contains(github.ref, '-rc') }}"
        title: "${{ github.event.repository.name }} ${{ env.RELEASE_VERSION }}"
        files: |
             ${{ github.event.repository.name }}.7z
